version: '3'

services:
    nginx:
      image: nginx
      container_name: nginx_container
      build:
        context: ./requirements/nginx
      volumes:
        -wordpress_volume:/var/www/html
      restart: always
      ports: 
       - "443:443"

    mariadb:
      image: mariadb
      container_name: db_container
      build:
        context: ./requirements/mariadb
      env_file: .env
      volumes:
        - mariadb_volume:/var/lib/mysql
      restart: always
      expose:
       - "3306"

    wordpress:
      image: wordpress
      container_name: wordpress_container
      build:
        context: ./requirements/wordpress-mac
      env_file: .env
      volumes:
        - wordpress_volume:/var/www/html
      restart: always
      expose:
        - "9000"

volumes:
  mariadb_volume:
      driver: local
      driver_opts:
        type: none
        device: ${HOME}/data/mariadb
        o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind