version: '3'

services:
    nginx:
      image: nginx
      container_name: nginx_container
      depends_on:
        - wordpress
      build:
        context: ./requirements/nginx
      volumes:
        - wordpress:/var/www/html
      restart: always
      ports: 
       - "443:443"

    mariadb:
      image: mariadb
      container_name: db_container
      build:
        context: ./requirements/mariadb
      env_file: .env
      volumes:
        - mariadb:/var/lib/mysql
      restart: always
      expose:
       - "3306"

    wordpress:
      image: wordpress
      container_name: wordpress_container
      depends_on:
        - mariadb
      build:
        context: ./requirements/wordpress
      env_file: .env
      volumes:
        - wordpress:/var/www/html
      restart: always
      expose:
        - "9000"

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind