version: '3'

services:
    nginx:
      image: nginx:latest
      container_name: nginx_container
      build:
        context: ./requirements/nginx
      ports: 
       - "443:443"

    mariadb:
      image: mariadb:latest
      container_name: db_container
      build:
        context: ./requirements/mariadb
      env_file: .env
      volumes:
        - /home/jordie/workspace/inception/data/mariadb:/var/lib/mysql
      expose:
       - "3306"

    wordpress:
      image: wordpress:latest
      container_name: wordpress_container
      build:
        context: ./requirements/wordpress
      env_file: .env
      volumes:
        - /home/jordie/workspace/inception/data/wordpress:/var/www/html
      expose:
        - "9000"